name: Remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
      - run: CI=false yarn build
      - name: ssh deploy on aws ec2
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          REMOTE_PORT: 3000
          SOURCE: "build/"
          TARGET: "~/yeeldbox/"
